mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: me.yi.hong.mybatis.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    url: jdbc:sqlite:E:/github/demo/mybatis/db/db.sqlite
    driver-class-name: org.sqlite.JDBC
